language: java
jdk:
  - oraclejdk7
  - openjdk7
cache:
  directories:
    - $HOME/.m2
env:
  global:
    - MAVEN_OPTS="-XX:MaxPermSize=2g -Xmx4g"
    - JAVA_OPTS="-XX:MaxPermSize=2g -Xmx4g"
install:
  - set -e
  - travis_retry sudo apt-get install -y --fix-missing libmagic1 libmagic-dev
  - gem install --no-ri --no-rdoc pdd
  - gem install --no-ri --no-rdoc est
  - set +e
script:
  - set -e
  - pdd --file=/dev/null --exclude=qulice-maven-plugin/src/it/**/*.java
  - est --dir=est --file=/dev/null
  - mvn clean install -Pqulice --errors
  - set +e
